import {
  Archive,
  BookOpen,
  Braces,
  Code2,
  Eraser,
  FileCode,
  FileImage,
  FileText,
  FileType,
  Grid3x3,
  Hash,
  Image as ImageIcon,
  ImagePlus,
  Images,
  PenTool,
  Presentation,
  Repeat,
  Scissors,
  Sheet,
  ShieldCheck,
  Type,
  Unlock,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type ToolCategoryId = "organize" | "convert" | "image" | "security";

export type ToolItem = {
  name: string;
  desc: string;
  href: string;
  icon: LucideIcon;
  color: string;
  bg: string;
  category: ToolCategoryId;
  /** Tanggal rilis fitur ("YYYY-MM-DD"); badge "New" hilang otomatis setelah 3 hari. */
  releasedAt?: string;
  /** Tampil di navbar sebagai shortcut primer (di luar dropdown). */
  primary?: boolean;
};

export const TOOL_CATEGORIES: {
  id: ToolCategoryId;
  label: string;
  description: string;
}[] = [
  {
    id: "organize",
    label: "Kelola PDF",
    description: "Gabung, pisah, susun, dan kompres dokumen",
  },
  {
    id: "convert",
    label: "Konversi",
    description: "Ubah antar format dokumen dan PDF",
  },
  {
    id: "image",
    label: "Gambar",
    description: "PDF ↔ gambar dan edit visual",
  },
  {
    id: "security",
    label: "Keamanan",
    description: "Lindungi atau buka kunci PDF",
  },
];

export const TOOLS: ToolItem[] = [
  {
    name: "Convert Apa Saja",
    desc: "Word, Excel, PowerPoint, gambar, HTML, Markdown, EPUB ke PDF — dan sebaliknya.",
    href: "/convert",
    icon: Repeat,
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
    primary: true,
  },
  {
    name: "Merge PDF",
    desc: "Gabungkan beberapa file PDF menjadi satu dokumen.",
    href: "/merge",
    icon: FileText,
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/30",
    category: "organize",
    primary: true,
  },
  {
    name: "Split PDF",
    desc: "Pisahkan PDF atau ekstrak halaman tertentu.",
    href: "/split",
    icon: Scissors,
    color: "text-rose-600 dark:text-rose-400",
    bg: "bg-rose-50 dark:bg-rose-900/30",
    category: "organize",
    primary: true,
  },
  {
    name: "Compress PDF",
    desc: "Kecilkan ukuran PDF tanpa mengorbankan kualitas.",
    href: "/compress",
    icon: Zap,
    color: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-50 dark:bg-amber-900/30",
    category: "organize",
    primary: true,
  },
  {
    name: "Organize PDF",
    desc: "Hapus, putar, atau atur ulang urutan halaman.",
    href: "/organize",
    icon: Grid3x3,
    color: "text-indigo-600 dark:text-indigo-400",
    bg: "bg-indigo-50 dark:bg-indigo-900/30",
    category: "organize",
  },
  {
    name: "Sign PDF",
    desc: "Tambahkan tanda tangan digital ke dokumen PDF.",
    href: "/sign",
    icon: PenTool,
    color: "text-slate-700 dark:text-slate-300",
    bg: "bg-slate-100 dark:bg-slate-800",
    category: "organize",
    primary: true,
  },
  {
    name: "Word to PDF",
    desc: "Ubah dokumen Word (.docx) menjadi PDF berkualitas tinggi.",
    href: "/docx-to-pdf",
    icon: FileCode,
    color: "text-indigo-600 dark:text-indigo-400",
    bg: "bg-indigo-50 dark:bg-indigo-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "Excel to PDF",
    desc: "Ubah Excel, ODS, atau CSV menjadi PDF rapi.",
    href: "/excel-to-pdf",
    icon: Sheet,
    color: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-50 dark:bg-emerald-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PowerPoint to PDF",
    desc: "Ubah presentasi PPT/PPTX menjadi PDF dengan font terjaga.",
    href: "/ppt-to-pdf",
    icon: Presentation,
    color: "text-orange-600 dark:text-orange-400",
    bg: "bg-orange-50 dark:bg-orange-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to Word",
    desc: "Ubah PDF menjadi DOC/DOCX yang mudah diedit.",
    href: "/pdf-to-word",
    icon: FileType,
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to Excel",
    desc: "Tarik data tabel PDF ke lembar kerja Excel.",
    href: "/pdf-to-excel",
    icon: Sheet,
    color: "text-green-600 dark:text-green-400",
    bg: "bg-green-50 dark:bg-green-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to PowerPoint",
    desc: "Ubah tiap halaman PDF menjadi slide PPTX.",
    href: "/pdf-to-powerpoint",
    icon: Presentation,
    color: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-50 dark:bg-amber-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to CSV",
    desc: "Ambil tabel dari PDF sebagai CSV siap analisis.",
    href: "/pdf-to-csv",
    icon: Sheet,
    color: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-50 dark:bg-emerald-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to Teks",
    desc: "Ekstrak teks PDF sebagai teks polos atau Markdown.",
    href: "/pdf-to-text",
    icon: Type,
    color: "text-sky-600 dark:text-sky-400",
    bg: "bg-sky-50 dark:bg-sky-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to HTML",
    desc: "Ubah PDF menjadi halaman HTML yang bisa dibuka di browser.",
    href: "/pdf-to-html",
    icon: Braces,
    color: "text-indigo-600 dark:text-indigo-400",
    bg: "bg-indigo-50 dark:bg-indigo-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to EPUB",
    desc: "Ubah PDF menjadi e-book yang nyaman dibaca di ponsel.",
    href: "/pdf-to-epub",
    icon: BookOpen,
    color: "text-violet-600 dark:text-violet-400",
    bg: "bg-violet-50 dark:bg-violet-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to PDF/A",
    desc: "Jadikan PDF memenuhi standar arsip jangka panjang.",
    href: "/pdf-to-pdfa",
    icon: Archive,
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "Teks to PDF",
    desc: "Ubah teks polos, RTF, atau ODT menjadi PDF.",
    href: "/txt-to-pdf",
    icon: Type,
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "Markdown to PDF",
    desc: "Ubah Markdown menjadi PDF dengan heading dan tabel.",
    href: "/markdown-to-pdf",
    icon: Hash,
    color: "text-sky-600 dark:text-sky-400",
    bg: "bg-sky-50 dark:bg-sky-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "HTML to PDF",
    desc: "Ubah berkas HTML menjadi PDF dengan gaya yang dirender.",
    href: "/html-to-pdf",
    icon: Code2,
    color: "text-indigo-600 dark:text-indigo-400",
    bg: "bg-indigo-50 dark:bg-indigo-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "EPUB to PDF",
    desc: "Ubah e-book EPUB menjadi PDF siap cetak.",
    href: "/epub-to-pdf",
    icon: BookOpen,
    color: "text-violet-600 dark:text-violet-400",
    bg: "bg-violet-50 dark:bg-violet-900/30",
    category: "convert",
    releasedAt: "2026-09-07",
  },
  {
    name: "Konversi Gambar",
    desc: "Ubah PNG, JPG, WEBP, dan SVG ke format lain.",
    href: "/image-converter",
    icon: Images,
    color: "text-teal-600 dark:text-teal-400",
    bg: "bg-teal-50 dark:bg-teal-900/30",
    category: "image",
    releasedAt: "2026-09-07",
  },
  {
    name: "Image to PDF",
    desc: "Ubah foto JPG, PNG, atau WEBP menjadi PDF.",
    href: "/image-to-pdf",
    icon: ImageIcon,
    color: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-50 dark:bg-emerald-900/30",
    category: "image",
    releasedAt: "2026-09-07",
  },
  {
    name: "JPG to PDF",
    desc: "Ubah gambar JPG menjadi PDF dengan pengaturan margin.",
    href: "/jpg-to-pdf",
    icon: ImagePlus,
    color: "text-yellow-600 dark:text-yellow-400",
    bg: "bg-yellow-50 dark:bg-yellow-900/30",
    category: "image",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to JPG",
    desc: "Ubah halaman PDF menjadi JPG, atau ekstrak gambar tertanam.",
    href: "/pdf-to-jpg",
    icon: FileImage,
    color: "text-yellow-600 dark:text-yellow-400",
    bg: "bg-yellow-50 dark:bg-yellow-900/30",
    category: "image",
    releasedAt: "2026-09-07",
  },
  {
    name: "PDF to PNG",
    desc: "Ubah halaman PDF menjadi PNG tajam tanpa lossy.",
    href: "/pdf-to-png",
    icon: FileImage,
    color: "text-violet-600 dark:text-violet-400",
    bg: "bg-violet-50 dark:bg-violet-900/30",
    category: "image",
    releasedAt: "2026-09-07",
  },
  {
    name: "Remove Background",
    desc: "Hapus background gambar dan unduh PNG transparan.",
    href: "/remove-bg",
    icon: Eraser,
    color: "text-fuchsia-600 dark:text-fuchsia-400",
    bg: "bg-fuchsia-50 dark:bg-fuchsia-900/30",
    category: "image",
    releasedAt: "2026-09-07",
  },
  {
    name: "Protect PDF",
    desc: "Lindungi PDF dengan kata sandi dan enkripsi.",
    href: "/protect-pdf",
    icon: ShieldCheck,
    color: "text-indigo-600 dark:text-indigo-400",
    bg: "bg-indigo-50 dark:bg-indigo-900/30",
    category: "security",
    releasedAt: "2026-09-07",
  },
  {
    name: "Unlock PDF",
    desc: "Hapus proteksi kata sandi dari file PDF.",
    href: "/unlock-pdf",
    icon: Unlock,
    color: "text-sky-600 dark:text-sky-400",
    bg: "bg-sky-50 dark:bg-sky-900/30",
    category: "security",
    releasedAt: "2026-09-07",
  },
];

export function getToolsByCategory(category: ToolCategoryId): ToolItem[] {
  return TOOLS.filter((tool) => tool.category === category);
}

export function getPrimaryNavTools(): ToolItem[] {
  return TOOLS.filter((tool) => tool.primary);
}
